steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo ${SHORT_SHA} && \
        echo ${COMMIT_SHA}
 options:
 logging: CLOUD_LOGGING_ONLY
